language: python
stages:
  - test

jobs:
  include:
    - stage: test
      before_script:
        - pip install -r requirements.txt
        - git submodule update --recursive --remote --merge
      script: python -m pytest test